export const OFFICIAL_MATCHES = [
  {
    "id": "match001",
    "matchNumber": 1,
    "group": "Grupo A",
    "teamA": "Mexico",
    "teamB": "South Africa",
    "flagA": "🇲🇽",
    "flagB": "🇿🇦",
    "dateUK": "2026-06-11",
    "timeUK": "20:00",
    "utc": "2026-06-11T19:00:00Z",
    "venue": "Mexico City, Mexico",
    "noteA": "Anfitrión: abre el Mundial 2026 en Ciudad de México.",
    "noteB": "",
    "realA": "",
    "realB": ""
  },
  {
    "id": "match002",
    "matchNumber": 2,
    "group": "Grupo A",
    "teamA": "South Korea",
    "teamB": "Czech Republic",
    "flagA": "🇰🇷",
    "flagB": "🇨🇿",
    "dateUK": "2026-06-12",
    "timeUK": "03:00",
    "utc": "2026-06-12T02:00:00Z",
    "venue": "Zapopan, Mexico",
    "noteA": "",
    "noteB": "",
    "realA": "",
    "realB": ""
  },
  {
    "id": "match003",
    "matchNumber": 3,
    "group": "Grupo B",
    "teamA": "Canada",
    "teamB": "Bosnia & Herzegovina",
    "flagA": "🇨🇦",
    "flagB": "🇧🇦",
    "dateUK": "2026-06-12",
    "timeUK": "20:00",
    "utc": "2026-06-12T19:00:00Z",
    "venue": "Toronto, Canada",
    "noteA": "Anfitrión: debuta en Toronto.",
    "noteB": "",
    "realA": "",
    "realB": ""
  },
  {
    "id": "match004",
    "matchNumber": 4,
    "group": "Grupo D",
    "teamA": "USA",
    "teamB": "Paraguay",
    "flagA": "🇺🇸",
    "flagB": "🇵🇾",
    "dateUK": "2026-06-13",
    "timeUK": "02:00",
    "utc": "2026-06-13T01:00:00Z",
    "venue": "Los Angeles, USA",
    "noteA": "Anfitrión: debuta en Los Angeles.",
    "noteB": "",
    "realA": "",
    "realB": ""
  },
  {
    "id": "match005",
    "matchNumber": 5,
    "group": "Grupo B",
    "teamA": "Qatar",
    "teamB": "Switzerland",
    "flagA": "🇶🇦",
    "flagB": "🇨🇭",
    "dateUK": "2026-06-13",
    "timeUK": "20:00",
    "utc": "2026-06-13T19:00:00Z",
    "venue": "Santa Clara, USA",
    "noteA": "",
    "noteB": "",
    "realA": "",
    "realB": ""
  },
  {
    "id": "match006",
    "matchNumber": 6,
    "group": "Grupo C",
    "teamA": "Brazil",
    "teamB": "Morocco",
    "flagA": "🇧🇷",
    "flagB": "🇲🇦",
    "dateUK": "2026-06-13",
    "timeUK": "23:00",
    "utc": "2026-06-13T22:00:00Z",
    "venue": "New Jersey, USA",
    "noteA": "Máximo campeón histórico del Mundial masculino.",
    "noteB": "Semifinalista en Qatar 2022.",
    "realA": "",
    "realB": ""
  },
  {
    "id": "match007",
    "matchNumber": 7,
    "group": "Grupo C",
    "teamA": "Haiti",
    "teamB": "Scotland",
    "flagA": "🇭🇹",
    "flagB": "🏴",
    "dateUK": "2026-06-14",
    "timeUK": "02:00",
    "utc": "2026-06-14T01:00:00Z",
    "venue": "Foxborough, USA",
    "noteA": "",
    "noteB": "Grupo exigente junto a Brasil y Marruecos.",
    "realA": "",
    "realB": ""
  },
  {
    "id": "match008",
    "matchNumber": 8,
    "group": "Grupo D",
    "teamA": "Australia",
    "teamB": "Turkey",
    "flagA": "🇦🇺",
    "flagB": "🇹🇷",
    "dateUK": "2026-06-14",
    "timeUK": "05:00",
    "utc": "2026-06-14T04:00:00Z",
    "venue": "Vancouver, Canada",
    "noteA": "",
    "noteB": "",
    "realA": "",
    "realB": ""
  },
  {
    "id": "match009",
    "matchNumber": 9,
    "group": "Grupo E",
    "teamA": "Germany",
    "teamB": "Curacao",
    "flagA": "🇩🇪",
    "flagB": "🇨🇼",
    "dateUK": "2026-06-14",
    "timeUK": "18:00",
    "utc": "2026-06-14T17:00:00Z",
    "venue": "Houston, USA",
    "noteA": "Selección tetracampeona mundial.",
    "noteB": "",
    "realA": "",
    "realB": ""
  },
  {
    "id": "match010",
    "matchNumber": 10,
    "group": "Grupo F",
    "teamA": "Netherlands",
    "teamB": "Japan",
    "flagA": "🇳🇱",
    "flagB": "🇯🇵",
    "dateUK": "2026-06-14",
    "timeUK": "21:00",
    "utc": "2026-06-14T20:00:00Z",
    "venue": "Arlington, USA",
    "noteA": "",
    "noteB": "",
    "realA": "",
    "realB": ""
  },
  {
    "id": "match011",
    "matchNumber": 11,
    "group": "Grupo E",
    "teamA": "Ivory Coast",
    "teamB": "Ecuador",
    "flagA": "🇨🇮",
    "flagB": "🇪🇨",
    "dateUK": "2026-06-15",
    "timeUK": "00:00",
    "utc": "2026-06-14T23:00:00Z",
    "venue": "Philadelphia, USA",
    "noteA": "",
    "noteB": "",
    "realA": "",
    "realB": ""
  },
  {
    "id": "match012",
    "matchNumber": 12,
    "group": "Grupo F",
    "teamA": "Sweden",
    "teamB": "Tunisia",
    "flagA": "🇸🇪",
    "flagB": "🇹🇳",
    "dateUK": "2026-06-15",
    "timeUK": "03:00",
    "utc": "2026-06-15T02:00:00Z",
    "venue": "Guadalupe, Mexico",
    "noteA": "",
    "noteB": "",
    "realA": "",
    "realB": ""
  },
  {
    "id": "match013",
    "matchNumber": 13,
    "group": "Grupo H",
    "teamA": "Spain",
    "teamB": "Cape Verde",
    "flagA": "🇪🇸",
    "flagB": "🇨🇻",
    "dateUK": "2026-06-15",
    "timeUK": "17:00",
    "utc": "2026-06-15T16:00:00Z",
    "venue": "Atlanta, USA",
    "noteA": "Campeón mundial 2010.",
    "noteB": "",
    "realA": "",
    "realB": ""
  },
  {
    "id": "match014",
    "matchNumber": 14,
    "group": "Grupo G",
    "teamA": "Belgium",
    "teamB": "Egypt",
    "flagA": "🇧🇪",
    "flagB": "🇪🇬",
    "dateUK": "2026-06-15",
    "timeUK": "20:00",
    "utc": "2026-06-15T19:00:00Z",
    "venue": "Seattle, USA",
    "noteA": "",
    "noteB": "",
    "realA": "",
    "realB": ""
  },
  {
    "id": "match015",
    "matchNumber": 15,
    "group": "Grupo H",
    "teamA": "Saudi Arabia",
    "teamB": "Uruguay",
    "flagA": "🇸🇦",
    "flagB": "🇺🇾",
    "dateUK": "2026-06-15",
    "timeUK": "23:00",
    "utc": "2026-06-15T22:00:00Z",
    "venue": "Miami, USA",
    "noteA": "",
    "noteB": "Bicampeón mundial.",
    "realA": "",
    "realB": ""
  },
  {
    "id": "match016",
    "matchNumber": 16,
    "group": "Grupo G",
    "teamA": "Iran",
    "teamB": "New Zealand",
    "flagA": "🇮🇷",
    "flagB": "🇳🇿",
    "dateUK": "2026-06-16",
    "timeUK": "02:00",
    "utc": "2026-06-16T01:00:00Z",
    "venue": "Los Angeles, USA",
    "noteA": "",
    "noteB": "",
    "realA": "",
    "realB": ""
  },
  {
    "id": "match017",
    "matchNumber": 17,
    "group": "Grupo I",
    "teamA": "France",
    "teamB": "Senegal",
    "flagA": "🇫🇷",
    "flagB": "🇸🇳",
    "dateUK": "2026-06-16",
    "timeUK": "20:00",
    "utc": "2026-06-16T19:00:00Z",
    "venue": "New Jersey, USA",
    "noteA": "Finalista de Qatar 2022.",
    "noteB": "",
    "realA": "",
    "realB": ""
  },
  {
    "id": "match018",
    "matchNumber": 18,
    "group": "Grupo I",
    "teamA": "Iraq",
    "teamB": "Norway",
    "flagA": "🇮🇶",
    "flagB": "🇳🇴",
    "dateUK": "2026-06-16",
    "timeUK": "23:00",
    "utc": "2026-06-16T22:00:00Z",
    "venue": "Foxborough, USA",
    "noteA": "",
    "noteB": "",
    "realA": "",
    "realB": ""
  },
  {
    "id": "match019",
    "matchNumber": 19,
    "group": "Grupo J",
    "teamA": "Argentina",
    "teamB": "Algeria",
    "flagA": "🇦🇷",
    "flagB": "🇩🇿",
    "dateUK": "2026-06-17",
    "timeUK": "02:00",
    "utc": "2026-06-17T01:00:00Z",
    "venue": "Kansas City, USA",
    "noteA": "Campeón vigente de Qatar 2022.",
    "noteB": "",
    "realA": "",
    "realB": ""
  },
  {
    "id": "match020",
    "matchNumber": 20,
    "group": "Grupo J",
    "teamA": "Austria",
    "teamB": "Jordan",
    "flagA": "🇦🇹",
    "flagB": "🇯🇴",
    "dateUK": "2026-06-17",
    "timeUK": "05:00",
    "utc": "2026-06-17T04:00:00Z",
    "venue": "Santa Clara, USA",
    "noteA": "",
    "noteB": "",
    "realA": "",
    "realB": ""
  },
  {
    "id": "match021",
    "matchNumber": 21,
    "group": "Grupo K",
    "teamA": "Portugal",
    "teamB": "DR Congo",
    "flagA": "🇵🇹",
    "flagB": "🇨🇩",
    "dateUK": "2026-06-17",
    "timeUK": "18:00",
    "utc": "2026-06-17T17:00:00Z",
    "venue": "Houston, USA",
    "noteA": "",
    "noteB": "",
    "realA": "",
    "realB": ""
  },
  {
    "id": "match022",
    "matchNumber": 22,
    "group": "Grupo L",
    "teamA": "England",
    "teamB": "Croatia",
    "flagA": "🏴",
    "flagB": "🇭🇷",
    "dateUK": "2026-06-17",
    "timeUK": "21:00",
    "utc": "2026-06-17T20:00:00Z",
    "venue": "Arlington, USA",
    "noteA": "Campeón mundial 1966.",
    "noteB": "Finalista 2018 y tercero en 2022.",
    "realA": "",
    "realB": ""
  },
  {
    "id": "match023",
    "matchNumber": 23,
    "group": "Grupo L",
    "teamA": "Ghana",
    "teamB": "Panama",
    "flagA": "🇬🇭",
    "flagB": "🇵🇦",
    "dateUK": "2026-06-18",
    "timeUK": "00:00",
    "utc": "2026-06-17T23:00:00Z",
    "venue": "Toronto, Canada",
    "noteA": "",
    "noteB": "",
    "realA": "",
    "realB": ""
  },
  {
    "id": "match024",
    "matchNumber": 24,
    "group": "Grupo K",
    "teamA": "Uzbekistan",
    "teamB": "Colombia",
    "flagA": "🇺🇿",
    "flagB": "🇨🇴",
    "dateUK": "2026-06-18",
    "timeUK": "03:00",
    "utc": "2026-06-18T02:00:00Z",
    "venue": "Mexico City, Mexico",
    "noteA": "",
    "noteB": "",
    "realA": "",
    "realB": ""
  },
  {
    "id": "match025",
    "matchNumber": 25,
    "group": "Grupo A",
    "teamA": "Czech Republic",
    "teamB": "South Africa",
    "flagA": "🇨🇿",
    "flagB": "🇿🇦",
    "dateUK": "2026-06-18",
    "timeUK": "17:00",
    "utc": "2026-06-18T16:00:00Z",
    "venue": "Atlanta, USA",
    "noteA": "",
    "noteB": "",
    "realA": "",
    "realB": ""
  },
  {
    "id": "match026",
    "matchNumber": 26,
    "group": "Grupo B",
    "teamA": "Switzerland",
    "teamB": "Bosnia & Herzegovina",
    "flagA": "🇨🇭",
    "flagB": "🇧🇦",
    "dateUK": "2026-06-18",
    "timeUK": "20:00",
    "utc": "2026-06-18T19:00:00Z",
    "venue": "Los Angeles, USA",
    "noteA": "",
    "noteB": "",
    "realA": "",
    "realB": ""
  },
  {
    "id": "match027",
    "matchNumber": 27,
    "group": "Grupo B",
    "teamA": "Canada",
    "teamB": "Qatar",
    "flagA": "🇨🇦",
    "flagB": "🇶🇦",
    "dateUK": "2026-06-18",
    "timeUK": "23:00",
    "utc": "2026-06-18T22:00:00Z",
    "venue": "Vancouver, Canada",
    "noteA": "Anfitrión: debuta en Toronto.",
    "noteB": "",
    "realA": "",
    "realB": ""
  },
  {
    "id": "match028",
    "matchNumber": 28,
    "group": "Grupo A",
    "teamA": "Mexico",
    "teamB": "South Korea",
    "flagA": "🇲🇽",
    "flagB": "🇰🇷",
    "dateUK": "2026-06-19",
    "timeUK": "02:00",
    "utc": "2026-06-19T01:00:00Z",
    "venue": "Zapopan, Mexico",
    "noteA": "Anfitrión: abre el Mundial 2026 en Ciudad de México.",
    "noteB": "",
    "realA": "",
    "realB": ""
  },
  {
    "id": "match029",
    "matchNumber": 29,
    "group": "Grupo D",
    "teamA": "USA",
    "teamB": "Australia",
    "flagA": "🇺🇸",
    "flagB": "🇦🇺",
    "dateUK": "2026-06-19",
    "timeUK": "20:00",
    "utc": "2026-06-19T19:00:00Z",
    "venue": "Seattle, USA",
    "noteA": "Anfitrión: debuta en Los Angeles.",
    "noteB": "",
    "realA": "",
    "realB": ""
  },
  {
    "id": "match030",
    "matchNumber": 30,
    "group": "Grupo C",
    "teamA": "Scotland",
    "teamB": "Morocco",
    "flagA": "🏴",
    "flagB": "🇲🇦",
    "dateUK": "2026-06-19",
    "timeUK": "23:00",
    "utc": "2026-06-19T22:00:00Z",
    "venue": "Foxborough, USA",
    "noteA": "Grupo exigente junto a Brasil y Marruecos.",
    "noteB": "Semifinalista en Qatar 2022.",
    "realA": "",
    "realB": ""
  },
  {
    "id": "match031",
    "matchNumber": 31,
    "group": "Grupo C",
    "teamA": "Brazil",
    "teamB": "Haiti",
    "flagA": "🇧🇷",
    "flagB": "🇭🇹",
    "dateUK": "2026-06-20",
    "timeUK": "01:30",
    "utc": "2026-06-20T00:30:00Z",
    "venue": "Philadelphia, USA",
    "noteA": "Máximo campeón histórico del Mundial masculino.",
    "noteB": "",
    "realA": "",
    "realB": ""
  },
  {
    "id": "match032",
    "matchNumber": 32,
    "group": "Grupo D",
    "teamA": "Turkey",
    "teamB": "Paraguay",
    "flagA": "🇹🇷",
    "flagB": "🇵🇾",
    "dateUK": "2026-06-20",
    "timeUK": "04:00",
    "utc": "2026-06-20T03:00:00Z",
    "venue": "Santa Clara, USA",
    "noteA": "",
    "noteB": "",
    "realA": "",
    "realB": ""
  },
  {
    "id": "match033",
    "matchNumber": 33,
    "group": "Grupo F",
    "teamA": "Netherlands",
    "teamB": "Sweden",
    "flagA": "🇳🇱",
    "flagB": "🇸🇪",
    "dateUK": "2026-06-20",
    "timeUK": "18:00",
    "utc": "2026-06-20T17:00:00Z",
    "venue": "Houston, USA",
    "noteA": "",
    "noteB": "",
    "realA": "",
    "realB": ""
  },
  {
    "id": "match034",
    "matchNumber": 34,
    "group": "Grupo E",
    "teamA": "Germany",
    "teamB": "Ivory Coast",
    "flagA": "🇩🇪",
    "flagB": "🇨🇮",
    "dateUK": "2026-06-20",
    "timeUK": "21:00",
    "utc": "2026-06-20T20:00:00Z",
    "venue": "Toronto, Canada",
    "noteA": "Selección tetracampeona mundial.",
    "noteB": "",
    "realA": "",
    "realB": ""
  },
  {
    "id": "match035",
    "matchNumber": 35,
    "group": "Grupo E",
    "teamA": "Ecuador",
    "teamB": "Curacao",
    "flagA": "🇪🇨",
    "flagB": "🇨🇼",
    "dateUK": "2026-06-21",
    "timeUK": "01:00",
    "utc": "2026-06-21T00:00:00Z",
    "venue": "Kansas City, USA",
    "noteA": "",
    "noteB": "",
    "realA": "",
    "realB": ""
  },
  {
    "id": "match036",
    "matchNumber": 36,
    "group": "Grupo F",
    "teamA": "Tunisia",
    "teamB": "Japan",
    "flagA": "🇹🇳",
    "flagB": "🇯🇵",
    "dateUK": "2026-06-21",
    "timeUK": "05:00",
    "utc": "2026-06-21T04:00:00Z",
    "venue": "Guadalupe, Mexico",
    "noteA": "",
    "noteB": "",
    "realA": "",
    "realB": ""
  },
  {
    "id": "match037",
    "matchNumber": 37,
    "group": "Grupo H",
    "teamA": "Spain",
    "teamB": "Saudi Arabia",
    "flagA": "🇪🇸",
    "flagB": "🇸🇦",
    "dateUK": "2026-06-21",
    "timeUK": "17:00",
    "utc": "2026-06-21T16:00:00Z",
    "venue": "Atlanta, USA",
    "noteA": "Campeón mundial 2010.",
    "noteB": "",
    "realA": "",
    "realB": ""
  },
  {
    "id": "match038",
    "matchNumber": 38,
    "group": "Grupo G",
    "teamA": "Belgium",
    "teamB": "Iran",
    "flagA": "🇧🇪",
    "flagB": "🇮🇷",
    "dateUK": "2026-06-21",
    "timeUK": "20:00",
    "utc": "2026-06-21T19:00:00Z",
    "venue": "Los Angeles, USA",
    "noteA": "",
    "noteB": "",
    "realA": "",
    "realB": ""
  },
  {
    "id": "match039",
    "matchNumber": 39,
    "group": "Grupo H",
    "teamA": "Uruguay",
    "teamB": "Cape Verde",
    "flagA": "🇺🇾",
    "flagB": "🇨🇻",
    "dateUK": "2026-06-21",
    "timeUK": "23:00",
    "utc": "2026-06-21T22:00:00Z",
    "venue": "Miami, USA",
    "noteA": "Bicampeón mundial.",
    "noteB": "",
    "realA": "",
    "realB": ""
  },
  {
    "id": "match040",
    "matchNumber": 40,
    "group": "Grupo G",
    "teamA": "New Zealand",
    "teamB": "Egypt",
    "flagA": "🇳🇿",
    "flagB": "🇪🇬",
    "dateUK": "2026-06-22",
    "timeUK": "02:00",
    "utc": "2026-06-22T01:00:00Z",
    "venue": "Vancouver, Canada",
    "noteA": "",
    "noteB": "",
    "realA": "",
    "realB": ""
  },
  {
    "id": "match041",
    "matchNumber": 41,
    "group": "Grupo J",
    "teamA": "Argentina",
    "teamB": "Austria",
    "flagA": "🇦🇷",
    "flagB": "🇦🇹",
    "dateUK": "2026-06-22",
    "timeUK": "18:00",
    "utc": "2026-06-22T17:00:00Z",
    "venue": "Arlington, USA",
    "noteA": "Campeón vigente de Qatar 2022.",
    "noteB": "",
    "realA": "",
    "realB": ""
  },
  {
    "id": "match042",
    "matchNumber": 42,
    "group": "Grupo I",
    "teamA": "France",
    "teamB": "Iraq",
    "flagA": "🇫🇷",
    "flagB": "🇮🇶",
    "dateUK": "2026-06-22",
    "timeUK": "22:00",
    "utc": "2026-06-22T21:00:00Z",
    "venue": "Philadelphia, USA",
    "noteA": "Finalista de Qatar 2022.",
    "noteB": "",
    "realA": "",
    "realB": ""
  },
  {
    "id": "match043",
    "matchNumber": 43,
    "group": "Grupo I",
    "teamA": "Norway",
    "teamB": "Senegal",
    "flagA": "🇳🇴",
    "flagB": "🇸🇳",
    "dateUK": "2026-06-23",
    "timeUK": "01:00",
    "utc": "2026-06-23T00:00:00Z",
    "venue": "Toronto, Canada",
    "noteA": "",
    "noteB": "",
    "realA": "",
    "realB": ""
  },
  {
    "id": "match044",
    "matchNumber": 44,
    "group": "Grupo J",
    "teamA": "Jordan",
    "teamB": "Algeria",
    "flagA": "🇯🇴",
    "flagB": "🇩🇿",
    "dateUK": "2026-06-23",
    "timeUK": "04:00",
    "utc": "2026-06-23T03:00:00Z",
    "venue": "Santa Clara, USA",
    "noteA": "",
    "noteB": "",
    "realA": "",
    "realB": ""
  },
  {
    "id": "match045",
    "matchNumber": 45,
    "group": "Grupo K",
    "teamA": "Portugal",
    "teamB": "Uzbekistan",
    "flagA": "🇵🇹",
    "flagB": "🇺🇿",
    "dateUK": "2026-06-23",
    "timeUK": "18:00",
    "utc": "2026-06-23T17:00:00Z",
    "venue": "Houston, USA",
    "noteA": "",
    "noteB": "",
    "realA": "",
    "realB": ""
  },
  {
    "id": "match046",
    "matchNumber": 46,
    "group": "Grupo L",
    "teamA": "England",
    "teamB": "Ghana",
    "flagA": "🏴",
    "flagB": "🇬🇭",
    "dateUK": "2026-06-23",
    "timeUK": "21:00",
    "utc": "2026-06-23T20:00:00Z",
    "venue": "Foxborough, USA",
    "noteA": "Campeón mundial 1966.",
    "noteB": "",
    "realA": "",
    "realB": ""
  },
  {
    "id": "match047",
    "matchNumber": 47,
    "group": "Grupo L",
    "teamA": "Panama",
    "teamB": "Croatia",
    "flagA": "🇵🇦",
    "flagB": "🇭🇷",
    "dateUK": "2026-06-24",
    "timeUK": "00:00",
    "utc": "2026-06-23T23:00:00Z",
    "venue": "Foxborough, USA",
    "noteA": "",
    "noteB": "Finalista 2018 y tercero en 2022.",
    "realA": "",
    "realB": ""
  },
  {
    "id": "match048",
    "matchNumber": 48,
    "group": "Grupo K",
    "teamA": "Colombia",
    "teamB": "DR Congo",
    "flagA": "🇨🇴",
    "flagB": "🇨🇩",
    "dateUK": "2026-06-24",
    "timeUK": "03:00",
    "utc": "2026-06-24T02:00:00Z",
    "venue": "Zapopan, Mexico",
    "noteA": "",
    "noteB": "",
    "realA": "",
    "realB": ""
  },
  {
    "id": "match049",
    "matchNumber": 49,
    "group": "Grupo B",
    "teamA": "Switzerland",
    "teamB": "Canada",
    "flagA": "🇨🇭",
    "flagB": "🇨🇦",
    "dateUK": "2026-06-24",
    "timeUK": "20:00",
    "utc": "2026-06-24T19:00:00Z",
    "venue": "Vancouver, Canada",
    "noteA": "",
    "noteB": "Anfitrión: debuta en Toronto.",
    "realA": "",
    "realB": ""
  },
  {
    "id": "match050",
    "matchNumber": 50,
    "group": "Grupo B",
    "teamA": "Bosnia & Herzegovina",
    "teamB": "Qatar",
    "flagA": "🇧🇦",
    "flagB": "🇶🇦",
    "dateUK": "2026-06-24",
    "timeUK": "20:00",
    "utc": "2026-06-24T19:00:00Z",
    "venue": "Seattle, USA",
    "noteA": "",
    "noteB": "",
    "realA": "",
    "realB": ""
  },
  {
    "id": "match051",
    "matchNumber": 51,
    "group": "Grupo C",
    "teamA": "Morocco",
    "teamB": "Haiti",
    "flagA": "🇲🇦",
    "flagB": "🇭🇹",
    "dateUK": "2026-06-24",
    "timeUK": "23:00",
    "utc": "2026-06-24T22:00:00Z",
    "venue": "Atlanta, USA",
    "noteA": "Semifinalista en Qatar 2022.",
    "noteB": "",
    "realA": "",
    "realB": ""
  },
  {
    "id": "match052",
    "matchNumber": 52,
    "group": "Grupo C",
    "teamA": "Scotland",
    "teamB": "Brazil",
    "flagA": "🏴",
    "flagB": "🇧🇷",
    "dateUK": "2026-06-24",
    "timeUK": "23:00",
    "utc": "2026-06-24T22:00:00Z",
    "venue": "Miami, USA",
    "noteA": "Grupo exigente junto a Brasil y Marruecos.",
    "noteB": "Máximo campeón histórico del Mundial masculino.",
    "realA": "",
    "realB": ""
  },
  {
    "id": "match053",
    "matchNumber": 53,
    "group": "Grupo A",
    "teamA": "South Africa",
    "teamB": "South Korea",
    "flagA": "🇿🇦",
    "flagB": "🇰🇷",
    "dateUK": "2026-06-25",
    "timeUK": "02:00",
    "utc": "2026-06-25T01:00:00Z",
    "venue": "Guadalupe, Mexico",
    "noteA": "",
    "noteB": "",
    "realA": "",
    "realB": ""
  },
  {
    "id": "match054",
    "matchNumber": 54,
    "group": "Grupo A",
    "teamA": "Czech Republic",
    "teamB": "Mexico",
    "flagA": "🇨🇿",
    "flagB": "🇲🇽",
    "dateUK": "2026-06-25",
    "timeUK": "02:00",
    "utc": "2026-06-25T01:00:00Z",
    "venue": "Mexico City, Mexico",
    "noteA": "",
    "noteB": "Anfitrión: abre el Mundial 2026 en Ciudad de México.",
    "realA": "",
    "realB": ""
  },
  {
    "id": "match055",
    "matchNumber": 55,
    "group": "Grupo E",
    "teamA": "Curacao",
    "teamB": "Ivory Coast",
    "flagA": "🇨🇼",
    "flagB": "🇨🇮",
    "dateUK": "2026-06-25",
    "timeUK": "21:00",
    "utc": "2026-06-25T20:00:00Z",
    "venue": "Philadelphia, USA",
    "noteA": "",
    "noteB": "",
    "realA": "",
    "realB": ""
  },
  {
    "id": "match056",
    "matchNumber": 56,
    "group": "Grupo E",
    "teamA": "Ecuador",
    "teamB": "Germany",
    "flagA": "🇪🇨",
    "flagB": "🇩🇪",
    "dateUK": "2026-06-25",
    "timeUK": "21:00",
    "utc": "2026-06-25T20:00:00Z",
    "venue": "New Jersey, USA",
    "noteA": "",
    "noteB": "Selección tetracampeona mundial.",
    "realA": "",
    "realB": ""
  },
  {
    "id": "match057",
    "matchNumber": 57,
    "group": "Grupo F",
    "teamA": "Tunisia",
    "teamB": "Netherlands",
    "flagA": "🇹🇳",
    "flagB": "🇳🇱",
    "dateUK": "2026-06-26",
    "timeUK": "00:00",
    "utc": "2026-06-25T23:00:00Z",
    "venue": "Kansas City, USA",
    "noteA": "",
    "noteB": "",
    "realA": "",
    "realB": ""
  },
  {
    "id": "match058",
    "matchNumber": 58,
    "group": "Grupo F",
    "teamA": "Japan",
    "teamB": "Sweden",
    "flagA": "🇯🇵",
    "flagB": "🇸🇪",
    "dateUK": "2026-06-26",
    "timeUK": "00:00",
    "utc": "2026-06-25T23:00:00Z",
    "venue": "Arlington, USA",
    "noteA": "",
    "noteB": "",
    "realA": "",
    "realB": ""
  },
  {
    "id": "match059",
    "matchNumber": 59,
    "group": "Grupo D",
    "teamA": "Turkey",
    "teamB": "USA",
    "flagA": "🇹🇷",
    "flagB": "🇺🇸",
    "dateUK": "2026-06-26",
    "timeUK": "03:00",
    "utc": "2026-06-26T02:00:00Z",
    "venue": "Los Angeles, USA",
    "noteA": "",
    "noteB": "Anfitrión: debuta en Los Angeles.",
    "realA": "",
    "realB": ""
  },
  {
    "id": "match060",
    "matchNumber": 60,
    "group": "Grupo D",
    "teamA": "Paraguay",
    "teamB": "Australia",
    "flagA": "🇵🇾",
    "flagB": "🇦🇺",
    "dateUK": "2026-06-26",
    "timeUK": "03:00",
    "utc": "2026-06-26T02:00:00Z",
    "venue": "Santa Clara, USA",
    "noteA": "",
    "noteB": "",
    "realA": "",
    "realB": ""
  },
  {
    "id": "match061",
    "matchNumber": 61,
    "group": "Grupo I",
    "teamA": "Norway",
    "teamB": "France",
    "flagA": "🇳🇴",
    "flagB": "🇫🇷",
    "dateUK": "2026-06-26",
    "timeUK": "20:00",
    "utc": "2026-06-26T19:00:00Z",
    "venue": "Foxborough, USA",
    "noteA": "",
    "noteB": "Finalista de Qatar 2022.",
    "realA": "",
    "realB": ""
  },
  {
    "id": "match062",
    "matchNumber": 62,
    "group": "Grupo I",
    "teamA": "Senegal",
    "teamB": "Iraq",
    "flagA": "🇸🇳",
    "flagB": "🇮🇶",
    "dateUK": "2026-06-26",
    "timeUK": "20:00",
    "utc": "2026-06-26T19:00:00Z",
    "venue": "Toronto, Canada",
    "noteA": "",
    "noteB": "",
    "realA": "",
    "realB": ""
  },
  {
    "id": "match063",
    "matchNumber": 63,
    "group": "Grupo H",
    "teamA": "Cape Verde",
    "teamB": "Saudi Arabia",
    "flagA": "🇨🇻",
    "flagB": "🇸🇦",
    "dateUK": "2026-06-27",
    "timeUK": "01:00",
    "utc": "2026-06-27T00:00:00Z",
    "venue": "Houston, USA",
    "noteA": "",
    "noteB": "",
    "realA": "",
    "realB": ""
  },
  {
    "id": "match064",
    "matchNumber": 64,
    "group": "Grupo H",
    "teamA": "Uruguay",
    "teamB": "Spain",
    "flagA": "🇺🇾",
    "flagB": "🇪🇸",
    "dateUK": "2026-06-27",
    "timeUK": "01:00",
    "utc": "2026-06-27T00:00:00Z",
    "venue": "Zapopan, Mexico",
    "noteA": "Bicampeón mundial.",
    "noteB": "Campeón mundial 2010.",
    "realA": "",
    "realB": ""
  },
  {
    "id": "match065",
    "matchNumber": 65,
    "group": "Grupo G",
    "teamA": "New Zealand",
    "teamB": "Belgium",
    "flagA": "🇳🇿",
    "flagB": "🇧🇪",
    "dateUK": "2026-06-27",
    "timeUK": "04:00",
    "utc": "2026-06-27T03:00:00Z",
    "venue": "Vancouver, Canada",
    "noteA": "",
    "noteB": "",
    "realA": "",
    "realB": ""
  },
  {
    "id": "match066",
    "matchNumber": 66,
    "group": "Grupo G",
    "teamA": "Egypt",
    "teamB": "Iran",
    "flagA": "🇪🇬",
    "flagB": "🇮🇷",
    "dateUK": "2026-06-27",
    "timeUK": "04:00",
    "utc": "2026-06-27T03:00:00Z",
    "venue": "Seattle, USA",
    "noteA": "",
    "noteB": "",
    "realA": "",
    "realB": ""
  },
  {
    "id": "match067",
    "matchNumber": 67,
    "group": "Grupo L",
    "teamA": "Panama",
    "teamB": "England",
    "flagA": "🇵🇦",
    "flagB": "🏴",
    "dateUK": "2026-06-27",
    "timeUK": "22:00",
    "utc": "2026-06-27T21:00:00Z",
    "venue": "New Jersey, USA",
    "noteA": "",
    "noteB": "Campeón mundial 1966.",
    "realA": "",
    "realB": ""
  },
  {
    "id": "match068",
    "matchNumber": 68,
    "group": "Grupo L",
    "teamA": "Croatia",
    "teamB": "Ghana",
    "flagA": "🇭🇷",
    "flagB": "🇬🇭",
    "dateUK": "2026-06-27",
    "timeUK": "22:00",
    "utc": "2026-06-27T21:00:00Z",
    "venue": "Philadelphia, USA",
    "noteA": "Finalista 2018 y tercero en 2022.",
    "noteB": "",
    "realA": "",
    "realB": ""
  },
  {
    "id": "match069",
    "matchNumber": 69,
    "group": "Grupo K",
    "teamA": "Colombia",
    "teamB": "Portugal",
    "flagA": "🇨🇴",
    "flagB": "🇵🇹",
    "dateUK": "2026-06-28",
    "timeUK": "00:30",
    "utc": "2026-06-27T23:30:00Z",
    "venue": "Miami, USA",
    "noteA": "",
    "noteB": "",
    "realA": "",
    "realB": ""
  },
  {
    "id": "match070",
    "matchNumber": 70,
    "group": "Grupo K",
    "teamA": "DR Congo",
    "teamB": "Uzbekistan",
    "flagA": "🇨🇩",
    "flagB": "🇺🇿",
    "dateUK": "2026-06-28",
    "timeUK": "00:30",
    "utc": "2026-06-27T23:30:00Z",
    "venue": "Atlanta, USA",
    "noteA": "",
    "noteB": "",
    "realA": "",
    "realB": ""
  },
  {
    "id": "match071",
    "matchNumber": 71,
    "group": "Grupo J",
    "teamA": "Algeria",
    "teamB": "Austria",
    "flagA": "🇩🇿",
    "flagB": "🇦🇹",
    "dateUK": "2026-06-28",
    "timeUK": "03:00",
    "utc": "2026-06-28T02:00:00Z",
    "venue": "Kansas City, USA",
    "noteA": "",
    "noteB": "",
    "realA": "",
    "realB": ""
  },
  {
    "id": "match072",
    "matchNumber": 72,
    "group": "Grupo J",
    "teamA": "Jordan",
    "teamB": "Argentina",
    "flagA": "🇯🇴",
    "flagB": "🇦🇷",
    "dateUK": "2026-06-28",
    "timeUK": "03:00",
    "utc": "2026-06-28T02:00:00Z",
    "venue": "Arlington, USA",
    "noteA": "",
    "noteB": "Campeón vigente de Qatar 2022.",
    "realA": "",
    "realB": ""
  },
  {
    "id": "match073",
    "matchNumber": 73,
    "group": "Dieciseisavos",
    "teamA": "2º Grupo A",
    "teamB": "2º Grupo B",
    "flagA": "",
    "flagB": "",
    "dateUK": "2026-06-28",
    "timeUK": "20:00",
    "utc": "2026-06-28T19:00:00Z",
    "venue": "Los Angeles, USA",
    "noteA": "",
    "noteB": "",
    "realA": "",
    "realB": ""
  },
  {
    "id": "match074",
    "matchNumber": 74,
    "group": "Dieciseisavos",
    "teamA": "1º Grupo E",
    "teamB": "3º Grupo A/B/C/D/F",
    "flagA": "",
    "flagB": "",
    "dateUK": "2026-06-29",
    "timeUK": "21:30",
    "utc": "2026-06-29T20:30:00Z",
    "venue": "Foxborough, USA",
    "noteA": "",
    "noteB": "",
    "realA": "",
    "realB": ""
  },
  {
    "id": "match075",
    "matchNumber": 75,
    "group": "Dieciseisavos",
    "teamA": "1º Grupo F",
    "teamB": "2º Grupo C",
    "flagA": "",
    "flagB": "",
    "dateUK": "2026-06-30",
    "timeUK": "02:00",
    "utc": "2026-06-30T01:00:00Z",
    "venue": "Guadalupe, Mexico",
    "noteA": "",
    "noteB": "",
    "realA": "",
    "realB": ""
  },
  {
    "id": "match076",
    "matchNumber": 76,
    "group": "Dieciseisavos",
    "teamA": "1º Grupo C",
    "teamB": "2º Grupo F",
    "flagA": "",
    "flagB": "",
    "dateUK": "2026-06-29",
    "timeUK": "18:00",
    "utc": "2026-06-29T17:00:00Z",
    "venue": "Houston, USA",
    "noteA": "",
    "noteB": "",
    "realA": "",
    "realB": ""
  },
  {
    "id": "match077",
    "matchNumber": 77,
    "group": "Dieciseisavos",
    "teamA": "1º Grupo I",
    "teamB": "3º Grupo C/D/F/G/H",
    "flagA": "",
    "flagB": "",
    "dateUK": "2026-06-30",
    "timeUK": "22:00",
    "utc": "2026-06-30T21:00:00Z",
    "venue": "New Jersey, USA",
    "noteA": "",
    "noteB": "",
    "realA": "",
    "realB": ""
  },
  {
    "id": "match078",
    "matchNumber": 78,
    "group": "Dieciseisavos",
    "teamA": "2º Grupo E",
    "teamB": "2º Grupo I",
    "flagA": "",
    "flagB": "",
    "dateUK": "2026-06-30",
    "timeUK": "18:00",
    "utc": "2026-06-30T17:00:00Z",
    "venue": "Arlington, USA",
    "noteA": "",
    "noteB": "",
    "realA": "",
    "realB": ""
  },
  {
    "id": "match079",
    "matchNumber": 79,
    "group": "Dieciseisavos",
    "teamA": "1º Grupo A",
    "teamB": "3º Grupo C/E/F/H/I",
    "flagA": "",
    "flagB": "",
    "dateUK": "2026-07-01",
    "timeUK": "02:00",
    "utc": "2026-07-01T01:00:00Z",
    "venue": "Mexico City, Mexico",
    "noteA": "",
    "noteB": "",
    "realA": "",
    "realB": ""
  },
  {
    "id": "match080",
    "matchNumber": 80,
    "group": "Dieciseisavos",
    "teamA": "1º Grupo L",
    "teamB": "3º Grupo E/H/I/J/K",
    "flagA": "",
    "flagB": "",
    "dateUK": "2026-07-01",
    "timeUK": "17:00",
    "utc": "2026-07-01T16:00:00Z",
    "venue": "Atlanta, USA",
    "noteA": "",
    "noteB": "",
    "realA": "",
    "realB": ""
  },
  {
    "id": "match081",
    "matchNumber": 81,
    "group": "Dieciseisavos",
    "teamA": "1º Grupo D",
    "teamB": "3º Grupo B/E/F/I/J",
    "flagA": "",
    "flagB": "",
    "dateUK": "2026-07-02",
    "timeUK": "01:00",
    "utc": "2026-07-02T00:00:00Z",
    "venue": "Santa Clara, USA",
    "noteA": "",
    "noteB": "",
    "realA": "",
    "realB": ""
  },
  {
    "id": "match082",
    "matchNumber": 82,
    "group": "Dieciseisavos",
    "teamA": "1º Grupo G",
    "teamB": "3º Grupo A/E/H/I/J",
    "flagA": "",
    "flagB": "",
    "dateUK": "2026-07-01",
    "timeUK": "21:00",
    "utc": "2026-07-01T20:00:00Z",
    "venue": "Seattle, USA",
    "noteA": "",
    "noteB": "",
    "realA": "",
    "realB": ""
  },
  {
    "id": "match083",
    "matchNumber": 83,
    "group": "Dieciseisavos",
    "teamA": "2º Grupo K",
    "teamB": "2º Grupo L",
    "flagA": "",
    "flagB": "",
    "dateUK": "2026-07-03",
    "timeUK": "00:00",
    "utc": "2026-07-02T23:00:00Z",
    "venue": "Toronto, Canada",
    "noteA": "",
    "noteB": "",
    "realA": "",
    "realB": ""
  },
  {
    "id": "match084",
    "matchNumber": 84,
    "group": "Dieciseisavos",
    "teamA": "1º Grupo H",
    "teamB": "2º Grupo J",
    "flagA": "",
    "flagB": "",
    "dateUK": "2026-07-02",
    "timeUK": "20:00",
    "utc": "2026-07-02T19:00:00Z",
    "venue": "Los Angeles, USA",
    "noteA": "",
    "noteB": "",
    "realA": "",
    "realB": ""
  },
  {
    "id": "match085",
    "matchNumber": 85,
    "group": "Dieciseisavos",
    "teamA": "1º Grupo B",
    "teamB": "3º Grupo E/F/G/I/J",
    "flagA": "",
    "flagB": "",
    "dateUK": "2026-07-03",
    "timeUK": "04:00",
    "utc": "2026-07-03T03:00:00Z",
    "venue": "Vancouver, Canada",
    "noteA": "",
    "noteB": "",
    "realA": "",
    "realB": ""
  },
  {
    "id": "match086",
    "matchNumber": 86,
    "group": "Dieciseisavos",
    "teamA": "1º Grupo J",
    "teamB": "2º Grupo H",
    "flagA": "",
    "flagB": "",
    "dateUK": "2026-07-03",
    "timeUK": "23:00",
    "utc": "2026-07-03T22:00:00Z",
    "venue": "Miami, USA",
    "noteA": "",
    "noteB": "",
    "realA": "",
    "realB": ""
  },
  {
    "id": "match087",
    "matchNumber": 87,
    "group": "Dieciseisavos",
    "teamA": "1º Grupo K",
    "teamB": "3º Grupo D/E/I/J/L",
    "flagA": "",
    "flagB": "",
    "dateUK": "2026-07-04",
    "timeUK": "02:30",
    "utc": "2026-07-04T01:30:00Z",
    "venue": "Kansas City, USA",
    "noteA": "",
    "noteB": "",
    "realA": "",
    "realB": ""
  },
  {
    "id": "match088",
    "matchNumber": 88,
    "group": "Dieciseisavos",
    "teamA": "2º Grupo D",
    "teamB": "2º Grupo G",
    "flagA": "",
    "flagB": "",
    "dateUK": "2026-07-03",
    "timeUK": "19:00",
    "utc": "2026-07-03T18:00:00Z",
    "venue": "Arlington, USA",
    "noteA": "",
    "noteB": "",
    "realA": "",
    "realB": ""
  },
  {
    "id": "match089",
    "matchNumber": 89,
    "group": "Octavos",
    "teamA": "Ganador partido 74",
    "teamB": "Ganador partido 77",
    "flagA": "",
    "flagB": "",
    "dateUK": "2026-07-04",
    "timeUK": "22:00",
    "utc": "2026-07-04T21:00:00Z",
    "venue": "Philadelphia, USA",
    "noteA": "",
    "noteB": "",
    "realA": "",
    "realB": ""
  },
  {
    "id": "match090",
    "matchNumber": 90,
    "group": "Octavos",
    "teamA": "Ganador partido 73",
    "teamB": "Ganador partido 75",
    "flagA": "",
    "flagB": "",
    "dateUK": "2026-07-04",
    "timeUK": "18:00",
    "utc": "2026-07-04T17:00:00Z",
    "venue": "Houston, USA",
    "noteA": "",
    "noteB": "",
    "realA": "",
    "realB": ""
  },
  {
    "id": "match091",
    "matchNumber": 91,
    "group": "Octavos",
    "teamA": "Ganador partido 76",
    "teamB": "Ganador partido 78",
    "flagA": "",
    "flagB": "",
    "dateUK": "2026-07-05",
    "timeUK": "21:00",
    "utc": "2026-07-05T20:00:00Z",
    "venue": "New Jersey, USA",
    "noteA": "",
    "noteB": "",
    "realA": "",
    "realB": ""
  },
  {
    "id": "match092",
    "matchNumber": 92,
    "group": "Octavos",
    "teamA": "Ganador partido 79",
    "teamB": "Ganador partido 80",
    "flagA": "",
    "flagB": "",
    "dateUK": "2026-07-06",
    "timeUK": "01:00",
    "utc": "2026-07-06T00:00:00Z",
    "venue": "Mexico City, Mexico",
    "noteA": "",
    "noteB": "",
    "realA": "",
    "realB": ""
  },
  {
    "id": "match093",
    "matchNumber": 93,
    "group": "Octavos",
    "teamA": "Ganador partido 83",
    "teamB": "Ganador partido 84",
    "flagA": "",
    "flagB": "",
    "dateUK": "2026-07-06",
    "timeUK": "20:00",
    "utc": "2026-07-06T19:00:00Z",
    "venue": "Arlington, USA",
    "noteA": "",
    "noteB": "",
    "realA": "",
    "realB": ""
  },
  {
    "id": "match094",
    "matchNumber": 94,
    "group": "Octavos",
    "teamA": "Ganador partido 81",
    "teamB": "Ganador partido 82",
    "flagA": "",
    "flagB": "",
    "dateUK": "2026-07-07",
    "timeUK": "01:00",
    "utc": "2026-07-07T00:00:00Z",
    "venue": "Seattle, USA",
    "noteA": "",
    "noteB": "",
    "realA": "",
    "realB": ""
  },
  {
    "id": "match095",
    "matchNumber": 95,
    "group": "Octavos",
    "teamA": "Ganador partido 86",
    "teamB": "Ganador partido 88",
    "flagA": "",
    "flagB": "",
    "dateUK": "2026-07-07",
    "timeUK": "17:00",
    "utc": "2026-07-07T16:00:00Z",
    "venue": "Atlanta, USA",
    "noteA": "",
    "noteB": "",
    "realA": "",
    "realB": ""
  },
  {
    "id": "match096",
    "matchNumber": 96,
    "group": "Octavos",
    "teamA": "Ganador partido 85",
    "teamB": "Ganador partido 87",
    "flagA": "",
    "flagB": "",
    "dateUK": "2026-07-07",
    "timeUK": "21:00",
    "utc": "2026-07-07T20:00:00Z",
    "venue": "Vancouver, Canada",
    "noteA": "",
    "noteB": "",
    "realA": "",
    "realB": ""
  },
  {
    "id": "match097",
    "matchNumber": 97,
    "group": "Cuartos",
    "teamA": "Ganador partido 89",
    "teamB": "Ganador partido 90",
    "flagA": "",
    "flagB": "",
    "dateUK": "2026-07-09",
    "timeUK": "21:00",
    "utc": "2026-07-09T20:00:00Z",
    "venue": "Foxborough, USA",
    "noteA": "",
    "noteB": "",
    "realA": "",
    "realB": ""
  },
  {
    "id": "match098",
    "matchNumber": 98,
    "group": "Cuartos",
    "teamA": "Ganador partido 93",
    "teamB": "Ganador partido 94",
    "flagA": "",
    "flagB": "",
    "dateUK": "2026-07-10",
    "timeUK": "20:00",
    "utc": "2026-07-10T19:00:00Z",
    "venue": "Los Angeles, USA",
    "noteA": "",
    "noteB": "",
    "realA": "",
    "realB": ""
  },
  {
    "id": "match099",
    "matchNumber": 99,
    "group": "Cuartos",
    "teamA": "Ganador partido 91",
    "teamB": "Ganador partido 92",
    "flagA": "",
    "flagB": "",
    "dateUK": "2026-07-11",
    "timeUK": "22:00",
    "utc": "2026-07-11T21:00:00Z",
    "venue": "Miami, USA",
    "noteA": "",
    "noteB": "",
    "realA": "",
    "realB": ""
  },
  {
    "id": "match100",
    "matchNumber": 100,
    "group": "Cuartos",
    "teamA": "Ganador partido 95",
    "teamB": "Ganador partido 96",
    "flagA": "",
    "flagB": "",
    "dateUK": "2026-07-12",
    "timeUK": "02:00",
    "utc": "2026-07-12T01:00:00Z",
    "venue": "Kansas City, USA",
    "noteA": "",
    "noteB": "",
    "realA": "",
    "realB": ""
  },
  {
    "id": "match101",
    "matchNumber": 101,
    "group": "Semifinal",
    "teamA": "Ganador partido 97",
    "teamB": "Ganador partido 98",
    "flagA": "",
    "flagB": "",
    "dateUK": "2026-07-14",
    "timeUK": "20:00",
    "utc": "2026-07-14T19:00:00Z",
    "venue": "Arlington, USA",
    "noteA": "",
    "noteB": "",
    "realA": "",
    "realB": ""
  },
  {
    "id": "match102",
    "matchNumber": 102,
    "group": "Semifinal",
    "teamA": "Ganador partido 99",
    "teamB": "Ganador partido 100",
    "flagA": "",
    "flagB": "",
    "dateUK": "2026-07-15",
    "timeUK": "20:00",
    "utc": "2026-07-15T19:00:00Z",
    "venue": "Atlanta, USA",
    "noteA": "",
    "noteB": "",
    "realA": "",
    "realB": ""
  },
  {
    "id": "match103",
    "matchNumber": 103,
    "group": "Tercer lugar",
    "teamA": "Perdedor partido 101",
    "teamB": "Perdedor partido 102",
    "flagA": "",
    "flagB": "",
    "dateUK": "2026-07-18",
    "timeUK": "22:00",
    "utc": "2026-07-18T21:00:00Z",
    "venue": "Miami, USA",
    "noteA": "",
    "noteB": "",
    "realA": "",
    "realB": ""
  },
  {
    "id": "match104",
    "matchNumber": 104,
    "group": "Final",
    "teamA": "Ganador partido 101",
    "teamB": "Ganador partido 102",
    "flagA": "",
    "flagB": "",
    "dateUK": "2026-07-19",
    "timeUK": "20:00",
    "utc": "2026-07-19T19:00:00Z",
    "venue": "New Jersey, USA",
    "noteA": "",
    "noteB": "",
    "realA": "",
    "realB": ""
  }
];
